apiVersion: v1
kind: Secret
metadata:
  name: mysql-greetings-secret
  labels:
    app: mysql-greetings
    app.kubernetes.io/part-of: greeting-app
    app.kubernetes.io/name: mysql-greetings
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DB_ROOT_PASSWORD: rootpasschange
  DB_USER: greetinguserchange
  DB_HOST_IP: 10.98.187.196 #update this with the ip address of the mysql service
  DB_PASSWORD: greetingpasschange
  DB_NAME: greeting_db
  DB_HOSTNAME: mysql-greetings
