apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-greetings
  labels:
    app: mysql-greetings
    app.kubernetes.io/name: mysql-greetings
    app.kubernetes.io/part-of: greeting-app
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-greetings
      app.kubernetes.io/name: mysql-greetings
      app.kubernetes.io/part-of: greeting-app
  template:
    metadata:
      labels:
        app: mysql-greetings
        app.kubernetes.io/name: mysql-greetings
        app.kubernetes.io/part-of: greeting-app
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-greetings-secret
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-greetings-secret
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-greetings-secret
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-greetings-secret
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-greetings-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-greetings
  labels:
    app: mysql-greetings
    app.kubernetes.io/part-of: greeting-app
    app.kubernetes.io/name: mysql-greetings
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql-greetings
  type: ClusterIP
