apiVersion: v1
kind: Secret
metadata:
  name: mysql-greetings-secret
  labels:
    app: mysql-greetings
    app.kubernetes.io/part-of: greeting-app
    app.kubernetes.io/name: mysql-greetings
    app.kubernetes.io/component: database
type: Opaque
stringData:
  database-name: greeting_db
  database-user: greetinguser
  database-password: greetingpass
  root-password: rootpass
