apiVersion: v1
kind: Secret
metadata:
  name: mysql-greetings-secret
  labels:
    app: mysql-greetings
    app.kubernetes.io/part-of: greeting-app
    app.kubernetes.io/name: mysql-greetings
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DB_ROOT_PASSWORD: rootpass
  DB_USER: greetinguser
  DB_PASSWORD: greetingpass
  DB_NAME: greeting_db
