apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: greeting-backend-allow-same-namespace
  namespace: 5b7aa5-dev
spec:
  podSelector:
    matchLabels:
      app: greeting-backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: 5b7aa5-dev
          podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 3001
    - from: [] # Explicitly deny all other traffic
      ports: [] # Block all other ports
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mysql-greetings
      ports:
        - protocol: TCP
          port: 3306
    - to: [] # Explicitly deny all other traffic
      ports: [] # Block all ports
